-- Compute quantity rules for materials line items.
-- trigger_mode = 'chained' so these fire AFTER add_line_item rules place materials on the quote.
-- Drywall: sqft/32 sheets | Paint: sqft/350 gallons | Tile: sqft*1.1 with waste factor

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-drywall', 'Compute Drywall Sheet Count from Sqft', 'Sets Materials: Drywall quantity to sqft / 32 (number of 4x8 sheets needed)', (SELECT id FROM rule_groups WHERE name = 'Drywall' LIMIT 1), 30, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Drywall","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Drywall","formula":"sqft / 32","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-interior-paint', 'Compute Interior Paint Gallons from Sqft', 'Sets Materials: Interior Paint quantity to sqft / 350 (gallons at 1 coat coverage)', (SELECT id FROM rule_groups WHERE name = 'Painting' LIMIT 1), 31, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Interior Paint","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Interior Paint","formula":"sqft / 350","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-shower-wall-tile', 'Compute Shower Wall Tile Sqft from Job Sqft', 'Sets Materials: Shower Wall Tile quantity to sqft * 1.1 (includes 10% waste factor)', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 32, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Shower Wall Tile","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Shower Wall Tile","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-bathroom-floor-tile', 'Compute Bathroom Floor Tile Sqft from Job Sqft', 'Sets Materials: Bathroom Floor Tile quantity to sqft * 1.1 (includes 10% waste factor)', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 33, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Bathroom Floor Tile","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Bathroom Floor Tile","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-bathroom-tile-supplies', 'Compute Bathroom Tile Supplies Sqft from Job Sqft', 'Sets Materials: Bathroom Tile Supplies quantity to sqft * 1.1 (includes 10% waste factor)', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 34, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Bathroom Tile Supplies","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Bathroom Tile Supplies","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));
