-- Compute quantity rules for flooring installation line items.
-- Flooring quantity = sqft directly (no rate variable needed).
-- Formula: sqft (quantity equals the resolved square footage of the job).
-- trigger_mode = 'on_create' since these are AI-matched items, not rule-added.

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-hardwood', 'Compute Hardwood Flooring Sqft', 'Sets Flooring: Install New Hardwood quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 40, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Install New Hardwood","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Install New Hardwood","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-laminate-basic', 'Compute Laminate Flooring Sqft (Basic)', 'Sets Flooring: Install new laminate flooring (Basic) quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 41, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Install new laminate flooring (Basic)","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Install new laminate flooring (Basic)","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-laminate-complex', 'Compute Laminate Flooring Sqft (Complex)', 'Sets Flooring: Install new laminate flooring (Complex) quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 42, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Install new laminate flooring (Complex)","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Install new laminate flooring (Complex)","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-vinyl', 'Compute Vinyl Flooring Sqft', 'Sets Flooring: Install new vinyl flooring quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 43, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Install new vinyl flooring","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Install new vinyl flooring","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-refinish', 'Compute Hardwood Refinish Sqft', 'Sets Flooring: Refinish Hardwood Floors quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 44, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Refinish Hardwood Floors","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Refinish Hardwood Floors","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-cork-underlayment', 'Compute Cork Underlayment Sqft', 'Sets Flooring: Cork Underlayment with Mastic Application quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 45, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Cork Underlayment with Mastic Application","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Cork Underlayment with Mastic Application","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-flooring-underlayment', 'Compute Underlayment Installation Sqft', 'Sets Flooring: Underlayment Installation quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 46, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Flooring: Underlayment Installation","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Flooring: Underlayment Installation","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));
