-- Compute quantity rules for remaining sqft-driven line items.
-- Exterior painting: sqft / paint_rate | Power wash: sqft / 200 | Ext paint: sqft / 350 gallons
-- Subfloor / insulation / masonry / wainscoting / wall paneling: sqft directly
-- Baseboard / crown molding: sqft / 2.5 (perimeter linear feet estimate)

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-exterior-painting', 'Compute Exterior Painting Hours from Sqft', 'Sets Exterior Painting quantity to sqft / paint_rate (100 sqft/hr)', (SELECT id FROM rule_groups WHERE name = 'Painting' LIMIT 1), 50, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Exterior Painting","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Exterior Painting","formula":"sqft / paint_rate","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-exterior-power-wash', 'Compute Power Wash Hours from Sqft', 'Sets Exterior: Power Wash and Paint Prep quantity to sqft / 200 (200 sqft/hr)', (SELECT id FROM rule_groups WHERE name = 'Exterior' LIMIT 1), 51, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Exterior: Power Wash and Paint Prep","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Exterior: Power Wash and Paint Prep","formula":"sqft / 200","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-exterior-paint', 'Compute Exterior Paint Gallons from Sqft', 'Sets Materials: Exterior Paint quantity to sqft / 350 (gallons at 1 coat coverage)', (SELECT id FROM rule_groups WHERE name = 'Painting' LIMIT 1), 52, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Exterior Paint","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Exterior Paint","formula":"sqft / 350","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-subfloor-plywood', 'Compute Plywood Subfloor Sqft', 'Sets Carpentry: Install New Plywood Sub Floor quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 53, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Install New Plywood Sub Floor","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Install New Plywood Sub Floor","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-subfloor-installation', 'Compute Subfloor Installation Sqft', 'Sets Carpentry: Subfloor Installation quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 54, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Subfloor Installation","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Subfloor Installation","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-wainscoting', 'Compute Wainscoting Sqft', 'Sets Carpentry: Wainscoting quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 55, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Wainscoting","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Wainscoting","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-wall-paneling', 'Compute Wall Paneling Sqft', 'Sets Carpentry: Wall Paneling quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 56, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Wall Paneling","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Wall Paneling","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-baseboard-trim', 'Compute Baseboard Trim Linear Feet from Sqft', 'Sets Carpentry: Install Baseboard Trim quantity to sqft / 2.5 (perimeter linear feet)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 57, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Install Baseboard Trim","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Install Baseboard Trim","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-baseboard-shoe', 'Compute Baseboard Shoe Linear Feet from Sqft', 'Sets Carpentry: Install Baseboard Shoe quantity to sqft / 2.5 (perimeter linear feet)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 58, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Install Baseboard Shoe","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Install Baseboard Shoe","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-baseboard-trim-and-shoe', 'Compute Baseboard Trim and Shoe Linear Feet from Sqft', 'Sets Carpentry: Install Baseboard Trim and Shoe quantity to sqft / 2.5 (perimeter linear feet)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 59, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Install Baseboard Trim and Shoe","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Install Baseboard Trim and Shoe","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-crown-molding', 'Compute Crown Molding Linear Feet from Sqft', 'Sets Carpentry: Crown Molding Installation quantity to sqft / 2.5 (perimeter linear feet)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 60, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Carpentry: Crown Molding Installation","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Carpentry: Crown Molding Installation","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-insulation-exterior-wall', 'Compute Exterior Wall Insulation Sqft', 'Sets Insulation: Insulate One Exterior Wall quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Insulation' LIMIT 1), 61, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Insulation: Insulate One Exterior Wall","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Insulation: Insulate One Exterior Wall","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-insulation-interior-ceiling', 'Compute Interior Ceiling Insulation Sqft', 'Sets Insulation: Insulate One Interior Ceiling quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Insulation' LIMIT 1), 62, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Insulation: Insulate One Interior Ceiling","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Insulation: Insulate One Interior Ceiling","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-insulation-interior-wall', 'Compute Interior Wall Insulation Sqft', 'Sets Insulation: Insulate One Interior Wall quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Insulation' LIMIT 1), 63, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Insulation: Insulate One Interior Wall","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Insulation: Insulate One Interior Wall","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-masonry-tuckpointing', 'Compute Tuckpointing Sqft', 'Sets Masonry: Tuckpointing quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Exterior' LIMIT 1), 64, 1, 'on_create', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Masonry: Tuckpointing","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Masonry: Tuckpointing","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));
