-- Price correction rules for all items added by rules with hardcoded $100 placeholder prices.
-- Uses set_unit_price chained rules to correct prices to match catalog values.
-- These fire after add_line_item rules place items on the quote.

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-baseboard-trim', 'Set Baseboard Trim Price', 'Corrects Carpentry: Install Baseboard Trim to catalog price $65/LF', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 80, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Carpentry: Install Baseboard Trim","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Carpentry: Install Baseboard Trim","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-baseboard-trim-and-shoe', 'Set Baseboard Trim and Shoe Price', 'Corrects Carpentry: Install Baseboard Trim and Shoe to catalog price $65/LF', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 81, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Carpentry: Install Baseboard Trim and Shoe","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Carpentry: Install Baseboard Trim and Shoe","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-demo', 'Set Demo Price', 'Corrects Demo to catalog price $70/hr', (SELECT id FROM rule_groups WHERE name = 'Demo' LIMIT 1), 82, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Demo","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Demo","unitPrice":70,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-debris-removal', 'Set Debris Removal Price', 'Corrects Debris Removal to catalog price $500', (SELECT id FROM rule_groups WHERE name = 'Demo' LIMIT 1), 83, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Debris Removal","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Debris Removal","unitPrice":500,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-cabinet-hanging', 'Set Cabinet Hanging Price', 'Corrects Carpentry: Cabinet Hanging to catalog price $200', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 84, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Carpentry: Cabinet Hanging","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Carpentry: Cabinet Hanging","unitPrice":200,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-light-switch', 'Set Light Switch Price', 'Corrects Electrical: Install New Light Switch to catalog price $250', (SELECT id FROM rule_groups WHERE name = 'Electrical' LIMIT 1), 85, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Electrical: Install New Light Switch","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Electrical: Install New Light Switch","unitPrice":250,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-interior-painting', 'Set Interior Painting Price', 'Corrects Interior Painting to catalog price $50/hr', (SELECT id FROM rule_groups WHERE name = 'Painting' LIMIT 1), 86, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Interior Painting","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Interior Painting","unitPrice":50,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-interior-painting-ceilings', 'Set Interior Painting Ceilings Price', 'Corrects Interior Painting: Ceilings to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Painting' LIMIT 1), 87, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Interior Painting: Ceilings","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Interior Painting: Ceilings","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-kitchen-sink-faucet', 'Set Kitchen Sink Faucet Price', 'Corrects Plumbing: Kitchen Sink Faucet Install to catalog price $120', (SELECT id FROM rule_groups WHERE name = 'Plumbing' LIMIT 1), 88, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Plumbing: Kitchen Sink Faucet Install","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Plumbing: Kitchen Sink Faucet Install","unitPrice":120,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-reconnect-gas-stove', 'Set Gas Stove Reconnect Price', 'Corrects Plumbing: Re-connect Gas Stove to catalog price $120', (SELECT id FROM rule_groups WHERE name = 'Plumbing' LIMIT 1), 89, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Plumbing: Re-connect Gas Stove","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Plumbing: Re-connect Gas Stove","unitPrice":120,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-shower-drain-rough', 'Set Shower Drain Rough Plumbing Price', 'Corrects Plumbing: Rough Connection for Shower Drain to catalog price $2500', (SELECT id FROM rule_groups WHERE name = 'Plumbing' LIMIT 1), 90, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Plumbing: Rough Connection for Shower Drain","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Plumbing: Rough Connection for Shower Drain","unitPrice":2500,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-shower-fixture', 'Set Shower Fixture Price', 'Corrects Plumbing: Install new Shower Fixture to catalog price $600', (SELECT id FROM rule_groups WHERE name = 'Plumbing' LIMIT 1), 91, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Plumbing: Install new Shower Fixture","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Plumbing: Install new Shower Fixture","unitPrice":600,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-framing-new-wall', 'Set Framing New Wall Price', 'Corrects Framing: Install new wall to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 92, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Framing: Install new wall","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Framing: Install new wall","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-drywall-install', 'Set Drywall Installation Price', 'Corrects Drywall: Installation of New Drywall to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Drywall' LIMIT 1), 93, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Drywall: Installation of New Drywall","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Drywall: Installation of New Drywall","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-drywall-ceiling', 'Set Drywall Ceiling Repairs Price', 'Corrects Drywall: Ceiling Repairs to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Drywall' LIMIT 1), 94, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Drywall: Ceiling Repairs","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Drywall: Ceiling Repairs","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-tile-shower-pan', 'Set Shower Pan Price', 'Corrects Tile: Construct Shower Pan to catalog price $1050', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 95, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Tile: Construct Shower Pan","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Tile: Construct Shower Pan","unitPrice":1050,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-tile-durock-surround', 'Set Durock Shower Surround Price', 'Corrects Tile: Install Durock Shower Surround to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 96, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Tile: Install Durock Shower Surround","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Tile: Install Durock Shower Surround","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-tile-tiled-shower', 'Set Tiled Shower Surround Price', 'Corrects Tile: Install Tiled Shower Surround to catalog price $75/sqft', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 97, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Tile: Install Tiled Shower Surround","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Tile: Install Tiled Shower Surround","unitPrice":75,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-tile-schluter', 'Set Schluter Tile Edge Trim Price', 'Corrects Tile: Schluter Tile Edge Trim to catalog price $65', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 98, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Tile: Schluter Tile Edge Trim","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Tile: Schluter Tile Edge Trim","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-tile-waterproof', 'Set Waterproof Shower Surround Price', 'Corrects Tile: Waterproof Shower Surround to catalog price $65/hr', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 99, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Tile: Waterproof Shower Surround","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Tile: Waterproof Shower Surround","unitPrice":65,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-materials-backsplash-tile', 'Set Backsplash Tile Supplies Price', 'Corrects Materials: Backsplash Tile Supplies to catalog price $250', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 100, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Materials: Backsplash Tile Supplies","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Materials: Backsplash Tile Supplies","unitPrice":250,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-materials-baseboard-supplies', 'Set Baseboard Supplies Price', 'Corrects Materials: Baseboard Supplies to catalog price $50', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 101, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Materials: Baseboard Supplies","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Materials: Baseboard Supplies","unitPrice":50,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-materials-durock', 'Set Durock Materials Price', 'Corrects Materials: Durock to catalog price $200', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 102, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Materials: Durock","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Materials: Durock","unitPrice":200,"matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('price-materials-shower-pan', 'Set Shower Pan Materials Price', 'Corrects Materials: Shower Pan to catalog price $150', (SELECT id FROM rule_groups WHERE name = 'Tile' LIMIT 1), 103, 1, 'chained', '{"type":"line_item_exists","productNamePattern":"Materials: Shower Pan","matchMode":"exact"}', '[{"type":"set_unit_price","productNamePattern":"Materials: Shower Pan","unitPrice":150,"matchMode":"exact"}]', datetime('now'), datetime('now'));
