-- Compute quantity rules for remaining materials items that scale with sqft.
-- Groups:
--   sqft * 1.1:  flooring materials (with 10% waste)
--   sqft:        insulation, vapor barrier, wainscoting, tuckpointing
--   sqft / 32:   plywood (sheets)
--   sqft / 2.5:  baseboard/shoe trim materials (linear feet)

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-hardwood-floor', 'Compute Hardwood Floor Materials Sqft', 'Sets Materials: Hardwood Floor quantity to sqft * 1.1 (10% waste)', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 36, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Hardwood Floor","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Hardwood Floor","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-laminate-flooring', 'Compute Laminate Flooring Materials Sqft', 'Sets Materials: Laminate Flooring quantity to sqft * 1.1 (10% waste)', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 37, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Laminate Flooring","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Laminate Flooring","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-vinyl-flooring', 'Compute Vinyl Flooring Materials Sqft', 'Sets Materials: Vinyl Flooring quantity to sqft * 1.1 (10% waste)', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 38, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Vinyl Flooring","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Vinyl Flooring","formula":"sqft * 1.1","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-insulation', 'Compute Insulation Materials Sqft', 'Sets Materials: Insulation quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Insulation' LIMIT 1), 39, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Insulation","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Insulation","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-vapor-barrier', 'Compute Vapor Barrier Sqft', 'Sets Materials: Vapor Barrier quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'General' LIMIT 1), 40, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Vapor Barrier","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Vapor Barrier","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-wainscotting', 'Compute Wainscotting Materials Sqft', 'Sets Materials: Wainscotting quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 41, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Wainscotting","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Wainscotting","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-tuckpointing', 'Compute Tuckpointing Materials Sqft', 'Sets Materials: Tuckpointing quantity to resolved sqft', (SELECT id FROM rule_groups WHERE name = 'Exterior' LIMIT 1), 42, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Tuckpointing","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Tuckpointing","formula":"sqft","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-plywood', 'Compute Plywood Sheet Count from Sqft', 'Sets Materials: Plywood quantity to sqft / 32 (4x8 sheets)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 43, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Plywood","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Plywood","formula":"sqft / 32","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-baseboard-trim-shoe', 'Compute Baseboard Trim and Shoe Materials Linear Feet', 'Sets Materials: Baseboard Trim and Shoe quantity to sqft / 2.5 (perimeter LF)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 44, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Baseboard Trim and Shoe","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Baseboard Trim and Shoe","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-shoe-trim', 'Compute Shoe Trim Materials Linear Feet', 'Sets Materials: Shoe Trim quantity to sqft / 2.5 (perimeter LF)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 45, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Shoe Trim","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Shoe Trim","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO rules (id, name, description, rule_group_id, priority_order, is_active, trigger_mode, condition_json, action_json, created_at, updated_at) VALUES ('cq-materials-molding-supplies', 'Compute Molding Supplies Linear Feet', 'Sets Materials: Molding Supplies quantity to sqft / 2.5 (perimeter LF)', (SELECT id FROM rule_groups WHERE name = 'Carpentry' LIMIT 1), 46, 1, 'chained', '{"type":"compound","conditions":[{"type":"line_item_exists","productNamePattern":"Materials: Molding Supplies","matchMode":"exact"},{"type":"request_text_extract","pattern":"(\\d[\\d,]*)\\s*(?:sq\\.?\\s*ft|square\\s*feet|sqft)","variableName":"sqft"}]}', '[{"type":"compute_quantity","productNamePattern":"Materials: Molding Supplies","formula":"sqft / 2.5","matchMode":"exact"}]', datetime('now'), datetime('now'));
